apiVersion: apps/v1
kind: Deployment
metadata:
  name: notes-web-client
  namespace: notes-app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: notes-web-client
    spec:
      containers:
        - name: notes-web-client
          image: gcr.io/kubernetes-course-lohika-2020/notes-web-client:0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8090
          readinessProbe:
            tcpSocket:
              port: 8090
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 5
          livenessProbe:
            tcpSocket:
              port: 8090
            initialDelaySeconds: 15
            periodSeconds: 20
            failureThreshold: 3
        - name: http-echo
          image: hashicorp/http-echo
          args:
            - "-text=hello"
          imagePullPolicy: Always
          ports:
            - containerPort: 5678
          readinessProbe:
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 5
            httpGet:
              path: /
              port: 5678
          livenessProbe:
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 5
            httpGet:
              path: /
              port: 5678
  selector:
    matchLabels:
      app: notes-web-client