apiVersion: apps/v1
kind: Deployment
metadata:
  name: notes-api
  namespace: notes-app
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: notes-api
    spec:
      containers:
        - name: notes-api
          image: gcr.io/kubernetes-course-lohika-2020/notes-api:0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: api-config
                  key: port
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: mongoDbHost
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: mongoDbPort
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: mongoDbName
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: mongo-db-secret
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-db-secret
                  key: password
          readinessProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 5
          livenessProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 20
            failureThreshold: 3
  selector:
    matchLabels:
      app: notes-api