kind: Service
apiVersion: v1
metadata:
  name: notes-api-loadbalancer-service
  namespace: notes-app
spec:
  selector:
    app: notes-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: LoadBalancer